### ISSUE TITLE
Failed to set up: cannot import name 'validate_dir' from 'pyhelpers.dirs'

### ISSUE THREAD

**Issue by Sanbecr** [morosanmihail/HA-LondonTfL#57]
I'd had v0.7.0 of the integration running for a few days, but since upgrading HA Core from 2026.3.x to 2026.4.2 all of the London TfL entities are failing to set up:

```
Logger: homeassistant.config_entries
Source: config_entries.py:769
First occurred: 08:47:39 (1 occurrence)
Last logged: 08:47:39

Error setting up entry 65 - Ealing Broadway for london_tfl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/london_tfl/__init__.py", line 31, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2683, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1181, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1106, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1280, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1312, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/london_tfl/sensor.py", line 34, in <module>
    from .tfl_data import TfLData
  File "/config/custom_components/london_tfl/tfl_data.py", line 11, in <module>
    from custom_components.london_tfl.codes import atco_to_crs
  File "/config/custom_components/london_tfl/codes.py", line 37, in <module>
    from pyrcs import LocationIdentifiers
  File "/usr/local/lib/python3.14/site-packages/pyrcs/__init__.py", line 9, in <module>
    from . import collector, converter, line_data, other_assets, parser, utils
  File "/usr/local/lib/python3.14/site-packages/pyrcs/collector.py", line 15, in <module>
    from .line_data import Bridges, ELRMileages, Electrification, LOR, LineNames, LocationIdentifiers, \
        TrackDiagrams
  File "/usr/local/lib/python3.14/site-packages/pyrcs/line_data/__init__.py", line 7, in <module>
    from .bridge import Bridges
  File "/usr/local/lib/python3.14/site-packages/pyrcs/line_data/bridge.py", line 12, in <module>
    from .._base import _Base
  File "/usr/local/lib/python3.14/site-packages/pyrcs/_base.py", line 14, in <module>
    from pyhelpers.dirs import cd, validate_dir
ImportError: cannot import name 'validate_dir' from 'pyhelpers.dirs' (/usr/local/lib/python3.14/site-packages/pyhelpers/dirs/__init__.py)
```

**Comment by morosanmihail** [comment]
Oh, thanks for the report! I'm also running 0.7.0 with 2026.4.2 and it's fine. 
I'll assume you've already tried reloading the integration and restarting HA.

I'll investigate what could cause this later tonight.

**Comment by Sanbecr** [comment]
Yep, I've tried both.

Thank you.
I'll also try and take a look and can help out with testing if you've got any pointers on where to start

**Comment by morosanmihail** [comment]
Appreciate the offer! Found one quick potential cause. Pushed 0.7.1. Try updating to that and do tell me if that fixed it.

**Comment by morosanmihail** [comment]
You can force HACS to find the update by going to the HACS entry for London TfL, then the 3 dots in the top right, then Update Information. That usually triggers the update to become available.

**Comment by Sanbecr** [comment]
Thank you, that's sorted it.
Incredibly fast fix!
